{
 "title": "Example Router Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "options": {
    "content": "# Example Router Dashboard\n\nThis is a sample [Apollo Router](https://router.apollo.dev) dashboard for Grafana that includes necessary metrics for the monitoring of a successful supergraph.\n\nThis is not fully complete, and each section should be vetted to ensure it meets your needs for your specific requirements. We've also added sections that can be removed as needed if the feature or data is not applicable, as well as sections where deployment-specific visualizations should be added."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "options": {
    "content": "# Helpful Links\n\nFor users of the dashboard, consider adding relevant links to your infrastructure; consider adding links to: \n\n* Your Apollo Studio instance for this graph (or all agraphs if desired)\n* Links to logging tools, ideally filtered for router-only logs\n* Links to runbooks for issues\n* Information about your supergraph"
   }
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Router request rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "requests"
    }
   ]
  },
  {
   "title": "Router Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(http_server_request_duration_seconds_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(http_server_request_duration_seconds_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(http_server_request_duration_seconds_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(http_server_request_duration_seconds_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "GraphQL Request Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count{graphql_errors!=\"true\"}[$__rate_interval])) / sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Error Codes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(code) (rate(apollo_router_graphql_error_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operation Request Metrics",
     "type": "text",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "options": {
      "content": "If desiring metrics by operation name, consider the amount of attribute cardinality this could include, as it would be N number of labels per operation name.\n\nThis is further compounded when adding other attributes, such as HTTP status codes or if there are errors. \n\nThe cardinality could introduce billing concerns in some APM tools (such as Datadog or New Relic) where metric cardinality is an important facet of pricing.\n\nFor request rates by operations: `sum by(graphql_operation_name) (rate(http_server_request_duration_seconds_count{graphql_operation_name!=\"IntrospectionQuery\"}[$__rate_interval]))`, and for p95s by operation: `histogram_quantile(0.95, sum by(le, graphql_operation_name) (rate(http_server_request_duration_seconds_bucket{graphql_operation_name!=\"IntrospectionQuery\"}[$__rate_interval])))`."
     },
     "targets": [
      {
       "expr": "sum by(graphql_operation_name) (rate(http_server_request_duration_seconds_count{graphql_operation_name!=\"IntrospectionQuery\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(http_response_status_code) (rate(http_server_request_duration_seconds_sum[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Request Rate by Subgraph",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(subgraph_name) (rate(http_client_request_duration_seconds_count{subgraph_name!=\"\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Latency (p95) by Subgraph",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, subgraph_name) (rate(http_client_request_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Subgraph Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(subgraph_name) (rate(http_client_request_duration_seconds_count{subgraph_name!=\"\", graphql_errors=\"true\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Opened Subscriptions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "apollo_router_opened_subscriptions",
       "legendFormat": "Opened Subscriptions"
      }
     ]
    }
   ]
  },
  { "title": "Coprocessors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Overall Coprocessor Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_operations_coprocessor_duration_bucket[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(apollo_router_operations_coprocessor_duration_bucket[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(apollo_router_operations_coprocessor_duration_bucket[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(apollo_router_operations_coprocessor_duration_bucket[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Coprocessor Latency (p95) by Stage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, coprocessor_stage) (rate(apollo_router_operations_coprocessor_duration_bucket[$__rate_interval])))",
     "legendFormat": "{{coprocessor_stage}}"
    }
   ]
  },
  {
   "title": "Coprocessor Metrics",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "options": {
    "content": "For coprocessors, we recommend also including details within this dashboard. Coprocessors are critical pieces of a router deployment, and as such, should be visible alongside core router metrics.\n\nConsider raising some of the metrics here to the overview or related sections (e.g. resources) as well."
   }
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "text",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "options": {
      "content": "This would ideally be a measurement of CPU usage per router instance.\n\nThis chart should also include upper and lower bounds for memory utilization, helping visualize both under- and over-provisioning at a glance, especially at a pod level. \n\nThis can help diagnose (for example) Kubernetes resource limit issues, or instances acting abnormally."
     }
    },
    {
     "title": "Memory Usage",
     "type": "text",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "options": {
      "content": "This would ideally be a measurement of memory usage per router instance.\n\nThis chart should also include upper and lower bounds for memory utilization, helping visualize both under- and over-provisioning at a glance, especially at a pod level. \n\nThis can help diagnose (for example) Kubernetes resource limit issues, or instances acting abnormally."
     }
    },
    {
     "title": "Other panels to consider",
     "type": "text",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 56 },
     "options": {
      "content": "Beyond general resource concerns (CPU, memory, potentially network throughput), it's also helpful to track datapoints specific to your infrastructure. \n\nIn general, we recommend tracking metrics both as a whole (in effect an average of resource consumption), as well as per-instance consumption. \n\nAs a result, it's often helpful to measure the number of instances being run as well, to help understand how much your supergraph may have scaled during operation.\n\nAdditionally, if using Kubernetes, usage against defined limits and pod/container restarts/backoffs can be helpful in troubleshooting. "
     }
    }
   ]
  },
  { "title": "Query Planning", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "Query Planning Total Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_query_planning_total_duration_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(apollo_router_query_planning_total_duration_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(apollo_router_query_planning_total_duration_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(apollo_router_query_planning_total_duration_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Query Planning p95 Total vs. Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_query_planning_total_duration_bucket{otel_scope_name=\"apollo/router\"}[$__rate_interval])))",
     "legendFormat": "total"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_query_planning_plan_duration_bucket[$__rate_interval])))",
     "legendFormat": "processing"
    }
   ]
  },
  {
   "title": "Estimated In-memory Query Plan Cache Size by Instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(instance) (apollo_router_cache_storage_estimated_size{kind=\"query planner\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Query Plan Cache Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(storage) (rate(apollo_router_cache_hit_time_count{kind=\"query planner\"}[$__rate_interval]))",
     "legendFormat": "{{storage}} - hit"
    },
    {
     "expr": "sum by(storage) (rate(apollo_router_cache_miss_time_count{kind=\"query planner\"}[$__rate_interval]))",
     "legendFormat": "{{storage}} - miss"
    }
   ]
  },
  {
   "title": "Query Planner Warmup Time (Last 24 hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_query_planning_warmup_duration_bucket[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Compute Jobs Queued",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 7, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apollo_router_compute_jobs_queued",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Schema Load Time (Last 24 hours)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_schema_load_duration_bucket[24h])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entity Caching",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 },
   "collapsed": true,
   "panels": [
    {
     "title": "Entity Caching Hits by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(entity_type) (rate(apollo_router_operations_entity_cache_hit_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Entity Caching Hits by Subgraph",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by(subgraph) (rate(apollo_router_operations_entity_cache_hit_bucket[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Uplink",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 68 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall Uplink Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le) (rate(apollo_router_uplink_fetch_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.9, sum by(le) (rate(apollo_router_uplink_fetch_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.75, sum by(le) (rate(apollo_router_uplink_fetch_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "p75"
      },
      {
       "expr": "histogram_quantile(0.5, sum by(le) (rate(apollo_router_uplink_fetch_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "p50"
      }
     ]
    },
    {
     "title": "p95 Uplink Latency by Kind",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum by(le, query) (rate(apollo_router_uplink_fetch_duration_seconds_bucket[$__rate_interval])))",
       "legendFormat": "{{kind}}"
      }
     ]
    },
    {
     "title": "Percent Uplink Failure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum by(query) (rate(apollo_router_uplink_fetch_count_total{status=\"failure\"}[$__rate_interval])) / sum by(query) (rate(apollo_router_uplink_fetch_count_total[$__rate_interval]))",
       "legendFormat": "{{query}}"
      }
     ]
    }
   ]
  }
 ]
}