{
 "title": "MCP Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "MCP Tool Call Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(apollo_mcp_tool_name) (rate(apollo_mcp_tool_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCP Tool Duration in ms (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, apollo_mcp_tool_name) (rate(apollo_mcp_tool_duration_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GraphQL Operation Call Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(apollo_mcp_operation_id) (rate(apollo_mcp_operation_count_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCP Operation Duration in ms (p95)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, apollo_mcp_operation_id) (rate(apollo_mcp_operation_duration_bucket[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCP Lifecycle Calls (Cumulative Sum)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(__name__) (apollo_mcp_initialize_count_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (apollo_mcp_list_tools_count_total)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (apollo_mcp_get_info_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MCP Tool error rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(apollo_mcp_tool_name) (rate(apollo_mcp_tool_count_total{apollo_mcp_success!=\"true\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}